name: Playwright Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npx playwright install
      - run: npx playwright test softstaking.spec.js --reporter=junit
        continue-on-error: true
      - run: ls -R
      - run: npm install -g tuskr
      - run: tuskr --project=${{ secrets.PLAYWRIGHTPROJECT }} --test-run-name="Basic playwright test TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" --api-token=${{ secrets.PLAYWRIGHTAPITOKEN }} --file="test-results/results.xml" --test-case-rules="rules/test-case-rules-basic.json"
