name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright tests with video and screenshot capture
        run: |
          npx playwright test basic/softstaking.spec.js --reporter=junit --video=on-first-retry --screenshot=only-on-failure
        continue-on-error: true

      - name: Install Tuskr CLI
        run: npm install -g tuskr

      - name: Collect screenshots and videos for failed tests
        run: |
          mkdir -p collected-artifacts
          # Copy the JUnit results file for Tuskr upload
          cp test-results/junit.xml collected-artifacts/

          # Collect the screenshots and videos only for failed tests
          find test-results -type f \( -name "*.png" -o -name "*.webm" \) -exec cp {} collected-artifacts/ \;

      - name: Create ZIP for Tuskr upload
        run: zip -r results.zip collected-artifacts/

      - name: Upload results to Tuskr
        run: |
          tuskr \
            --project=${{ secrets.PLAYWRIGHTPROJECT }} \
            --test-run-name="Basic playwright test TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" \
            --api-token=${{ secrets.PLAYWRIGHTAPITOKEN }} \
            --file="results.zip" \
            --test-case-rules="rules/test-case-rules-basic.json"
