name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - run: npm ci

      # Install Playwright browsers
      - run: npx playwright install

      # Run Playwright tests
      - run: npx playwright test softstaking.spec.js
        continue-on-error: true  # Continue even if tests fail (so artifacts still upload)

      # Install Tuskr CLI
      - run: npm install -g tuskr

      # ✅ Collect screenshots, videos, and results.xml into a flat folder
      - name: Collect screenshots and videos
        run: |
          mkdir -p test-artifacts
          find test-results -type f \( -name "*.png" -o -name "*.webm" \) -exec cp {} test-artifacts/ \;
          cp results.xml test-artifacts/

      # ✅ Zip the contents
      - name: Create ZIP for Tuskr upload
        run: |
          cd test-artifacts
          zip -r ../results.zip .

      # ✅ Upload to Tuskr
      - name: Push results to Tuskr
        run: |
          tuskr \
            --project=${{ secrets.PLAYWRIGHTPROJECT }} \
            --test-run-name="Basic playwright test TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" \
            --api-token=${{ secrets.PLAYWRIGHTAPITOKEN }} \
            --file="results.zip" \
            --test-case-rules="rules/test-case-rules-basic.json"
