name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - run: npm ci

      # Install Playwright browsers
      - run: npx playwright install

      # Run Playwright tests (continue even if tests fail)
      - run: npx playwright test softstaking.spec.js
        continue-on-error: true

      # Install Tuskr CLI
      - run: npm install -g tuskr

      # Prepare test results for upload (zip results + screenshots)
      - name: Zip results with screenshots/videos
        run: |
          mkdir upload-folder
          cp results.xml upload-folder/ || echo "No results.xml found"
          cp -r test-results upload-folder/test-results || echo "No test-results found"
          cp -r playwright-report upload-folder/playwright-report || echo "No playwright-report found"
          cd upload-folder && zip -r ../results.zip . && cd ..

      # Push test results to Tuskr
      - name: Push results to Tuskr
        run: |
          IST_TIMESTAMP=$(TZ='Asia/Kolkata' date +'%Y-%m-%d_%H-%M-%S')
          tuskr --project=${{ secrets.PLAYWRIGHTPROJECT }} \
                --test-run-name="Basic playwright test TIMESTAMP=$IST_TIMESTAMP" \
                --api-token=${{ secrets.PLAYWRIGHTAPITOKEN }} \
                --file="results.zip" \
                --test-case-rules="rules/test-case-rules-basic.json"
